//! Agreement between the committed wire-contract JSON Schema artifact and the
//! strict custom-resource request decoder.
//!
//! `RawDeploymentRequest` (and every nested `Raw*` struct) declares its wire
//! keys with `#[serde(rename_all = "PascalCase")]`, `deny_unknown_fields`, and
//! serde defaults that decide requiredness. The TypeScript side declares the
//! same contract once in `contract/wire-contract.mjs` and renders it to
//! `contract/wire-schema.json`. Nothing derives one side from the other, so
//! this test binds them: it loads the committed artifact and asserts the
//! decoder agrees with it in both directions. A rename, an added key, a
//! dropped key, or a requiredness change on either side alone fails here.
//!
//! The artifact is regenerated by `scripts/generate-wire-schema.mjs` and the
//! `verify:wire-contract` gate fails when it drifts from the schema, so this
//! test always exercises the exact artifact that will be committed.

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use serde_json::{Map, Value};

    use crate::request::RawDeploymentRequest;

    const WIRE_SCHEMA_PATH: &str =
        concat!(env!("CARGO_MANIFEST_DIR"), "/../contract/wire-schema.json");

    /// The optional nested tuning paths no verification scenario configures;
    /// they must be exercised explicitly so a rename on either side cannot
    /// hide behind missing coverage.
    const UNCOVERED_OPTIONAL_PATHS: &[&[&str]] = &[
        &["Transfer", "AdvancedTuning", "SourceBlockBytes"],
        &["Transfer", "AdvancedTuning", "SourceBlockMergeGapBytes"],
        &["Transfer", "AdvancedTuning", "SourceGetConcurrency"],
        &["Transfer", "AdvancedTuning", "SourceWindowBytes"],
        &["Transfer", "AdvancedTuning", "SourceWindowMemoryBudgetMiB"],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "MaxAttempts",
        ],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "BaseDelayMs",
        ],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "MaxDelayMs",
        ],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "SlowdownBaseDelayMs",
        ],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "SlowdownMaxDelayMs",
        ],
        &[
            "Transfer",
            "AdvancedTuning",
            "DestinationWriteRetry",
            "Jitter",
        ],
    ];

    /// An object node of the artifact: its property path in the payload, its
    /// declared properties, and the keys the schema marks required.
    struct ObjectNode {
        path: Vec<String>,
        properties: Vec<(String, Value)>,
        required: BTreeSet<String>,
    }

    fn load_schema() -> Value {
        let text = std::fs::read_to_string(WIRE_SCHEMA_PATH).unwrap_or_else(|error| {
            panic!("cannot read the committed wire-schema artifact at {WIRE_SCHEMA_PATH}: {error}")
        });
        serde_json::from_str(&text)
            .unwrap_or_else(|error| panic!("wire-schema artifact is not valid JSON: {error}"))
    }

    /// Builds a payload that carries every property path the artifact
    /// declares, with schema-valid values, so the accepted side of the
    /// contract is exercised exhaustively (including every optional field).
    fn build_payload(schema: &Value) -> Value {
        if let Some(branches) = schema.get("anyOf").and_then(Value::as_array) {
            for branch in branches {
                if branch.get("type").and_then(Value::as_str) == Some("null") {
                    continue;
                }
                return build_payload(branch);
            }
        }
        match schema.get("type").and_then(Value::as_str) {
            Some("object") => {
                let mut map = Map::new();
                if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
                    for (key, child) in properties {
                        map.insert(key.clone(), build_payload(child));
                    }
                }
                Value::Object(map)
            }
            Some("array") => {
                let items = schema.get("items").cloned().unwrap_or(Value::Null);
                Value::Array(vec![build_payload(&items)])
            }
            Some("string") => match schema.get("enum").and_then(Value::as_array) {
                Some(values) => values
                    .first()
                    .cloned()
                    .unwrap_or_else(|| Value::String("value".into())),
                None => Value::String("value".into()),
            },
            Some("integer") | Some("number") => Value::from(1u64),
            Some("boolean") => Value::Bool(true),
            Some("null") => Value::Null,
            _ => {
                if let Some(types) = schema.get("type").and_then(Value::as_array) {
                    for kind in types {
                        if kind.as_str() == Some("null") {
                            continue;
                        }
                        let mut branch = schema.clone();
                        branch["type"] = kind.clone();
                        return build_payload(&branch);
                    }
                }
                // Unconstrained ("any", the envelope fields typed as Value):
                // null is the only shape every unknown payload shares; the
                // envelope fields accept it, and if a future field makes this
                // fallback invalid the decode assertion below fails loudly.
                Value::Null
            }
        }
    }

    /// Collects every object node with declared properties, descending into
    /// anyOf branches, nested properties, and array items.
    fn collect_object_nodes(schema: &Value, path: &mut Vec<String>, out: &mut Vec<ObjectNode>) {
        if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
            let required = schema
                .get("required")
                .and_then(Value::as_array)
                .map(|list| {
                    list.iter()
                        .filter_map(Value::as_str)
                        .map(str::to_string)
                        .collect::<BTreeSet<_>>()
                })
                .unwrap_or_default();
            assert_eq!(
                schema.get("additionalProperties"),
                Some(&Value::Bool(false)),
                "wire-schema object {} is not strict: the decoder's deny_unknown_fields \
                 contract would be wider than the schema",
                path_label(path),
            );
            out.push(ObjectNode {
                path: path.clone(),
                properties: properties
                    .iter()
                    .map(|(key, child)| (key.clone(), child.clone()))
                    .collect(),
                required,
            });
        }
        if let Some(branches) = schema.get("anyOf").and_then(Value::as_array) {
            for branch in branches {
                collect_object_nodes(branch, path, out);
            }
        }
        if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
            for (key, child) in properties {
                path.push(key.clone());
                collect_object_nodes(child, path, out);
                path.pop();
            }
        }
        if let Some(items) = schema.get("items") {
            path.push("[0]".to_string());
            collect_object_nodes(items, path, out);
            path.pop();
        }
    }

    fn path_label(path: &[String]) -> String {
        if path.is_empty() {
            "(root)".to_string()
        } else {
            path.join(".")
        }
    }

    /// Navigates to the object at `path` (whose final segment names a key
    /// inside an object) and applies `edit`.
    fn edit_object<F>(payload: &mut Value, path: &[String], edit: F)
    where
        F: FnOnce(&mut Map<String, Value>),
    {
        let mut node = payload;
        for segment in path {
            let next = if segment == "[0]" {
                node.as_array_mut()
                    .and_then(|array| array.get_mut(0))
                    .unwrap_or_else(|| panic!("payload path {} missing", path_label(path)))
            } else {
                node.as_object_mut()
                    .and_then(|map| map.get_mut(segment))
                    .unwrap_or_else(|| panic!("payload path {} missing", path_label(path)))
            };
            node = next;
        }
        edit(node.as_object_mut().unwrap_or_else(|| {
            panic!(
                "payload path {} does not resolve to an object",
                path_label(path)
            )
        }));
    }

    fn decode(payload: &Value) -> Result<RawDeploymentRequest, serde_json::Error> {
        serde_json::from_value::<RawDeploymentRequest>(payload.clone())
    }

    fn path_present(payload: &Value, path: &[&str]) -> bool {
        let mut node = payload;
        for segment in path {
            let Some(next) = node.as_object().and_then(|map| map.get(*segment)) else {
                return false;
            };
            node = next;
        }
        true
    }

    #[test]
    fn decoder_accepts_every_property_path_the_schema_declares() {
        let schema = load_schema();
        let payload = build_payload(&schema);

        // The optional nested tuning fields have no scenario coverage; prove
        // the built payload carries every one of them under its exact wire
        // name before decoding.
        for path in UNCOVERED_OPTIONAL_PATHS {
            assert!(
                path_present(&payload, path),
                "the schema-derived payload is missing {}",
                path.join(".")
            );
        }

        decode(&payload).unwrap_or_else(|error| {
            panic!(
                "the decoder rejects a payload built from every schema-declared \
                 property path; the Rust wire names drifted from the schema: {error}"
            )
        });
    }

    #[test]
    fn decoder_rejects_unknown_properties_the_schema_does_not_declare() {
        let schema = load_schema();
        let payload = build_payload(&schema);
        let mut nodes = Vec::new();
        collect_object_nodes(&schema, &mut Vec::new(), &mut nodes);

        for node in &nodes {
            let mut bogus = payload.clone();
            let bogus_key = "NotARealProperty";
            edit_object(&mut bogus, &node.path, |map| {
                map.insert(bogus_key.to_string(), Value::Bool(true));
            });
            assert!(
                decode(&bogus).is_err(),
                "the decoder accepted {} at {}; the decoder's accepted key set is \
                 wider than the schema",
                bogus_key,
                path_label(&node.path)
            );
        }
    }

    #[test]
    fn decoder_requiredness_matches_the_schema() {
        let schema = load_schema();
        let payload = build_payload(&schema);
        let mut nodes = Vec::new();
        collect_object_nodes(&schema, &mut Vec::new(), &mut nodes);

        for node in &nodes {
            for (key, _) in &node.properties {
                let mut variant = payload.clone();
                edit_object(&mut variant, &node.path, |map| {
                    map.remove(key);
                });
                let result = decode(&variant);
                if node.required.contains(key) {
                    assert!(
                        result.is_err(),
                        "the decoder accepted {} without {}; the schema marks it \
                         required",
                        path_label(&node.path),
                        key
                    );
                } else {
                    assert!(
                        result.is_ok(),
                        "the decoder rejected {} without {}; the schema marks it \
                         optional",
                        path_label(&node.path),
                        key
                    );
                }
            }
        }
    }

    #[test]
    fn schema_artifact_is_the_root_object_contract() {
        let schema = load_schema();
        assert!(
            schema.get("properties").is_some(),
            "artifact root is not an object"
        );
        assert!(
            schema.get("required").is_some(),
            "artifact root declares no required keys"
        );
        assert_eq!(
            schema.get("additionalProperties"),
            Some(&Value::Bool(false)),
            "artifact root must be strict"
        );
        // Smoke the wire names that historically diverged.
        let properties = schema["properties"].as_object().expect("root properties");
        assert!(properties.contains_key("CloudfrontInvalidation"));
        let advanced_tuning =
            schema["properties"]["Transfer"]["properties"]["AdvancedTuning"]["properties"]
                .as_object()
                .expect("AdvancedTuning properties");
        assert!(advanced_tuning.contains_key("SourceWindowMemoryBudgetMiB"));
    }
}
